// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDAz75LNzXLkVAzyCmHpduQE7fJokTuP4',
    appId: '1:94633419383:web:250d51ae7cdec7051a5c72',
    messagingSenderId: '94633419383',
    projectId: 'parkbangla-882ff',
    authDomain: 'parkbangla-882ff.firebaseapp.com',
    storageBucket: 'parkbangla-882ff.firebasestorage.app',
    measurementId: 'G-HVNCR2EZWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7rQXGsTODHHiJJH6kOjifWifIkjNBTSA',
    appId: '1:94633419383:android:dc3ded2c7b3efea81a5c72',
    messagingSenderId: '94633419383',
    projectId: 'parkbangla-882ff',
    storageBucket: 'parkbangla-882ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEoZkdaImLCeJdAcuNaDWoOTdSpEUVZ0g',
    appId: '1:94633419383:ios:c245facb4d1e8ced1a5c72',
    messagingSenderId: '94633419383',
    projectId: 'parkbangla-882ff',
    storageBucket: 'parkbangla-882ff.firebasestorage.app',
    iosBundleId: 'com.parkbangla.parkbanglaMobile',
  );

}